package org.com.rarp.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import org.com.rarp.interfaces.Consulta;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-01T15:19:15.717-02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "consulta/consultaSOAP", 
                  wsdlLocation = "http://localhost:8080/rarpws/consulta/consultaSOAP?wsdl",
                  targetNamespace = "http://SOAP.rarp.com.org/") 
public class ConsultaSOAP extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://SOAP.rarp.com.org/", "consulta/consultaSOAP");
    public final static QName ConsultaSOAPPort = new QName("http://SOAP.rarp.com.org/", "ConsultaSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/rarpws/consulta/consultaSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConsultaSOAP.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/rarpws/consulta/consultaSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConsultaSOAP(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConsultaSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSOAP() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ConsultaSOAP(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConsultaSOAP(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConsultaSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Consulta
     */
    @WebEndpoint(name = "ConsultaSOAPPort")
    public Consulta getConsultaSOAPPort() {
        return super.getPort(ConsultaSOAPPort, Consulta.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Consulta
     */
    @WebEndpoint(name = "ConsultaSOAPPort")
    public Consulta getConsultaSOAPPort(WebServiceFeature... features) {
        return super.getPort(ConsultaSOAPPort, Consulta.class, features);
    }

}
