package org.com.rarp.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-12-01T15:19:15.655-02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://interfaces.rarp.com.org/", name = "Consulta")
@XmlSeeAlso({ObjectFactory.class})
public interface Consulta {

    @WebMethod
    @RequestWrapper(localName = "sevidorOn", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.SevidorOn")
    @ResponseWrapper(localName = "sevidorOnResponse", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.SevidorOnResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean sevidorOn(
        @WebParam(name = "usuario", targetNamespace = "")
        org.com.rarp.interfaces.Usuario usuario
    ) throws Exception_Exception;

    @WebMethod(operationName = "EnviaResposta")
    @RequestWrapper(localName = "EnviaResposta", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.EnviaResposta")
    @ResponseWrapper(localName = "EnviaRespostaResponse", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.EnviaRespostaResponse")
    public void enviaResposta(
        @WebParam(name = "resposta", targetNamespace = "")
        org.com.rarp.interfaces.Resposta resposta
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "getRequisicoes", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.GetRequisicoes")
    @ResponseWrapper(localName = "getRequisicoesResponse", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.GetRequisicoesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.com.rarp.interfaces.Requisicao> getRequisicoes() throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "consultar", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.Consultar")
    @ResponseWrapper(localName = "consultarResponse", targetNamespace = "http://interfaces.rarp.com.org/", className = "org.com.rarp.interfaces.ConsultarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<org.com.rarp.interfaces.Resposta> consultar(
        @WebParam(name = "requisicao", targetNamespace = "")
        org.com.rarp.interfaces.Requisicao requisicao
    ) throws Exception_Exception;
}
